version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:D4,egilter@db:5050/personeldb
    networks:
      - appnet

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: personeldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D4,egilter
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  postgres-data:


networks:
  appnet:
